-- Create the user_otps table
create table if not exists public.user_otps (
  id bigint generated by default as identity primary key,
  user_id bigint references public.myusers(id) on delete cascade,
  otp varchar(6) not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

-- Add index for faster lookups
create index if not exists idx_user_otps_user_id on public.user_otps(user_id);

-- Enable RLS
alter table public.user_otps enable row level security;

-- Create policies
create policy "Enable all access for authenticated users"
  on public.user_otps
  for all
  using (true)
  with check (true); 